//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using PaymentEngine.Internal.Commands.Paying;


namespace PaymentEngine.Paying
{
    public partial class PaymentNotificationHandler : IHandleMessages<PaymentNotification>
    {
		
		public void Handle(PaymentNotification message)
		{
			// Handle message on partial class
			this.HandleImplementation(message);
		}

		partial void HandleImplementation(PaymentNotification message);

        public IBus Bus { get; set; }

    }

	
}
