
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using NServiceBus;
using PaymentEngine.Internal.Commands.Payments;
using PaymentEngine.Payments;


  namespace PaymentEngine.Ecommerce.Controllers
{
    public partial class TestMessagesController : Controller
    {
        //
        // GET: /TestMessages/

        public ActionResult Index()
        {
            return View();
        }

		
	    

        //
        // POST: /TestMessages/SendMessageSubmitPayment
          
        public ISubmitPaymentSender SubmitPaymentSender { get; set; }
          
        [HttpPost]
        public ActionResult SendMessageSubmitPayment(SubmitPayment SubmitPayment)
        {
            ConfigureSubmitPayment(SubmitPayment);
            SubmitPaymentSender.Send(SubmitPayment);

            ViewBag.MessageSent = "SubmitPayment";

            return View("Index");
        }

		
        partial void ConfigureSubmitPayment(SubmitPayment message);
      
    }
}
