//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using PaymentEngine.Internal.Commands.Payments;


namespace PaymentEngine.Payments
{
    public partial class SubmitPaymentSender : ISubmitPaymentSender, ServiceMatrix.Shared.INServiceBusComponent
    {
		
        public void Send(SubmitPayment message)
        {
            ConfigureSubmitPayment(message);
            Bus.Send(message);
        }

        partial void ConfigureSubmitPayment(SubmitPayment message);

        public IBus Bus { get; set; }

    }

	
	public partial interface ISubmitPaymentSender
    {
        
        void Send(SubmitPayment message);

	}

	
}
